# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0007_auto_20190621_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='add_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='add caption'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='caption'),
        ),
    ]
